sudo: required
services:
  - docker

before_install:
  - docker build -t lmalunin/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run lmalunin/react-test npm test -- --coverage

after_success:
  - docker build -t lmalunin/multi-client ./client
  - docker build -t lmalunin/multi-nginx ./nginx
  - docker build -t lmalunin/multi-server ./server
  - docker build -t lmalunin/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push lmalunin/multi-client
  - docker push lmalunin/multi-nginx
  - docker push lmalunin/multi-server
  - docker push lmalunin/multi-worker
