sudo: required
services:
  - docker

before_install:
  - docker build -t lm/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run lm/react-test npm test -- --coverage

after_success:
  - docker build -t lm/multi-client ./client
  - docker build -t lm/multi-nginx ./nginx
  - docker build -t lm/multi-server ./server
  - docker build -t lm/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push lm/multi-client
  - docker push lm/multi-nginx
  - docker push lm/multi-server
  - docker push lm/multi-worker
